### ISSUE TITLE
Error on third turn on external camera

### ISSUE THREAD

**Issue by JNUTONGNIU** [FIRST-Tech-Challenge/SkyStone#121]
This error occurs when we turn on the external camera for the third time on the cell phone used by our team. please give your comment ，Please advise the solution

![Error](https://user-images.githubusercontent.com/45326909/68443289-75f4da00-020e-11ea-877f-fa826493651c.jpg)

**Comment by FROGbots-4634** [comment]
I have a ***strong*** feeling this is related to this: https://github.com/ftctechnh/ftc_app/issues/681

**Comment by JNUTONGNIU** [comment]
> I have a _**strong**_ feeling this is related to this: [ftctechnh/ftc_app#681](https://github.com/ftctechnh/ftc_app/issues/681)

thank you for your help,I wonder if you can solve this problem now?You said you would integrate your own UVC driver, if possible, please also provide us, because we are now difficult to solve!Thank you very much.

**Comment by FROGbots-4634** [comment]
@JNUTONGNIU I never did get around to integrating a 3rd party UVC driver myself.... I have no knowledge of USB and my knowledge of C/C++ is pretty limited, and I decided it wasn't really worth the time since simply unplugging and replugging the camera allows it to run again. So if you unplug and replug the camera before each match it will work out OK.

**Comment by JNUTONGNIU** [comment]
> @JNUTONGNIU我从来没有自己集成过第三方UVC驱动程序。...我不了解USB，而且我对C / C ++的了解非常有限，而且我认为从拔掉插头开始就不值得花时间了然后重新插上相机，即可重新运行。因此，如果您在每次比赛前都拔下相机并重新插上电源，它将正常工作。

Ok, thank you very much for your help
