### ISSUE TITLE
Issues with "Hub Firmware" section of Inspection activities

### ISSUE THREAD

**Issue by FROGbots-4634** [FIRST-Tech-Challenge/SkyStone#19]
So there's two separate (but related) issues here:

 1. If no Expansion Hubs are connected, then firmware is reported by the DS as "N/A" (which is fine), but the RC simply shows a blank space. See the below screenshot:

    ![Untitled](https://user-images.githubusercontent.com/26417650/62654225-53aca100-b92d-11e9-9282-f5f5dd3daf3e.png)

 2. If an Expansion Hub IS connected, the Driver Station still shows "N/A" even though the RC shows the correct firmware version.

**Comment by NoahAndrews** [comment]
I believe point 2 is expected behavior, as by definition the Driver Station can't have a hub firmware version.

**Comment by FROGbots-4634** [comment]
@NoahAndrews hmm, then perhaps that TextView should be dynamically hidden if `inspectingRobotController()` is false?

**Comment by NoahAndrews** [comment]
For that matter, I believe point 1 is expected behavior as well. If there are no hubs connected, there's no firmware version to report.

**Comment by cmacfarl** [comment]
The Driver Station N/A is by design.

At to the RC, I'm not a fan of hiding things in this sort of instance.   Nor do I see this as an actual bug.  The lack of a firmware version should tell an inspector, and/or a teammate, trying to figure out why the robot controller isn't seeing a expansion hub that there's a problem somewhere.   Of course they already know there's a problem if a configuration is loaded that's looking for an EH as that's reported in the main activity.   I'm also not necessarily convinced that adding some text there would be of any further value.  

My view overall matches Noah's in that this is expected behavior.
