### ISSUE TITLE
Please add PIDF for 13.7:1 GoBilda 

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/SkyStone#24]
With the additional PIDF being given for motors, I would like to request the Matrix motors with the GoBilda 13.7:1 Gearbox.

Thank you,

Alan
Rookie Coach FTC #16072, Quantum Quacks

**Comment by qwertyquerty** [comment]
Still waiting for this

**Comment by gearsincorg** [comment]
The recently released Ver 5.3 SDK has configuration options and PIDF values for the 5201 and 5202 goBILDA motors.

These two Motor Configurations are suitable for all gear ratios, since the encoders are located on the motor shaft (not output shaft) and the direction of rotation is not effected by the gear ratio.

The actual motor performance will depend largely on your specific robot application and configuration, so the same PIDF values are also applicable to all gear ratios.

**Comment by cmacfarl** [comment]
Thanks @gearsincorg 

Please reopen if you have further questions or feel this is not adequate.

**Comment by AlecHub** [comment]
So why are there gearbox specific configurations for the NeveRest and REV base motors?

**Comment by gearsincorg** [comment]
Some of the Gearbox related stuff is historic, from back when the motor velocity API was proportional to the "nominal top speed" of the chosen motor.  So it was necessary to "know" what the top speed encoder counts were.    Now, the motor velocity methods all relate to absolute counts per second, so if the encoders are on the motor shaft, they are not impacted by gearbox ratios.

However, the Neverest gearboxes are not planetary gears, so the direction of rotation IS different for the various ratios.  Since there is still some code in the SDK that attempts to keep track of what direction the shaft is rotating (i'm not exactly sure why) these different configurations have been retained.  In reality, they also probably aren't necessary.

Sometimes deciding to remove dead wood is a tough decision,and requires extensive testing..

**Comment by AlecHub** [comment]
So you need specific configurations for the goBILDA 5201 and 5202 series because the output shafts of the 5201 and 5202 rotate in opposite directions, one is spur gear and the other is planetary gear, all of the above, none of the above?

**Comment by WestsideRobotics** [comment]
.
To expand a bit on Phil's comment.  It was and remains a slight benefit for teams when the FTC app began to standardize the direction of rotation (to CW) when positive Power is commanded.

Previously teams needed to remember that NR 20 (Legacy and Orbital) and Tetrix motors rotate CW with positive raw voltage, while NR 40 and NR 60 rotate CCW with positive raw voltage.  Now, the only surprise (and some confusion) comes when teams hot-wire a motor for testing and get a different result than the code provides.

A notable exception still is the REV Core Hex motor which rotates **opposite** the printed white arrow when positive Power is commanded.

With the advent of new motor and gearbox options, it pays to just know your hardware -- always a good lesson for teams.
.

**Comment by gearsincorg** [comment]
> So you need specific configurations for the goBILDA 5201 and 5202 series because the output shafts of the 5201 and 5202 gearboxes rotate in opposite directions, one is spur gear and the other is planetary gear, all of the above, none of the above?

More than anything, because the user needs to be able to select a motor type during configuration,, and it would be too generic just to put goBILDA as the only choice.  .  There was no long-term guarantee that the motor /encoder combinations would be identical across the two model lines.  So keeping them separate seemed like a good idea.

**Comment by AlecHub** [comment]
So currently there is no difference between the 5201 and 5202 configurations.  I don't have an issue with that.  Just trying to understand.  If and when either series of gearboxes gets a new base motor/encoder, the we may see a 520x-B configuration.
