### ISSUE TITLE
5.5 is missing Javadoc

### ISSUE THREAD

**Issue by alan412** [FIRST-Tech-Challenge/SkyStone#259]
The 5.5 release candidate does not have Javadoc under doc/

**Comment by FROGbots-4634** [comment]
v5.5 now pulls javadoc, AARs, and source JARs from bintray.

**Comment by alan412** [comment]
It did not pull javadoc when I built using Android Studio 4.0.1 on a mac.
I did a find . -name 'javadoc' from the root to make sure it didn't go
someplace else.

**Comment by FROGbots-4634** [comment]
Well, at least on my computer, Android Studio knows where to find the JavaDoc:

![Screenshot from 2020-08-26 11-01-58](https://user-images.githubusercontent.com/26417650/91320803-ed8afa00-e78b-11ea-8bc2-748b09ee1e4c.png)

**Comment by cmacfarl** [comment]
The javadoc jar is going to be in your gradle cache.  Which on windows is <users>/.gradle/caches/modules-2/files-2.1/org.firstinspires.ftc

However, upon closer inspection it looks like gradle may not have packaged the javadocs in the jars properly.   Will investigate.

The decision to move to packaging the javadoc as an artifact instead of raw files within the docs directory is intentional.  This decision may be revisited prior to the release of v6.0.

**Comment by cmacfarl** [comment]
To help clarify where @FROGbots-4634 got that view, within AS switch your project pane view to 'Project' and then you can right click on the library in question and select 'Library Properties'

**Comment by alan412** [comment]
I can see them in my Library Properties.  the reason my "find" didn't find
them is because they aren't in my project directory but in my gradle cache.


How do I get students to look at the JavaDoc from within AndroidStudio?
 (ie, the equivalent of before looking at index.html to be able to look
through it)

One other advantage of the javadoc html in the repo is it makes it very
easy to see API changes between versions.

**Comment by cmacfarl** [comment]
Also now pushed to GitHub Pages.  https://first-tech-challenge.github.io/SkyStone/
