### ISSUE TITLE
Does anybody have any success with using ConceptTensorFlowObjectDetection.java?

### ISSUE THREAD

**Issue by Hellositsme** [FIRST-Tech-Challenge/SkyStone#47]
Yesterday we tried to use ConceptTensorFlowObjectDetection.java. We got some rectangles returned from Tensorflow, but the rectangles group both the stones and skystones together and it's not predictable. Is this model final? If anybody has better success than us, please share your tips. Thanks!

**Comment by FROGbots-4634** [comment]
@Hellositsme for detecting the targets on the SkyStones you'll want to use Vuforia

**Comment by cmacfarl** [comment]
Tensorflow was trained to detect stones.  To the best of my knowledge it was not trained to distinguish between stones and skystones.  That is why there are image targets on the skystones.  As @FROGbots-4634 you need to use Vuforia for that.

**Comment by ftctechnh** [comment]
Hellsitsme

The Tensorflow model that is included with the Skystone software was trained to recognize the Stones and the Skystones for this season's game.  

When you ran the ConceptTensorFlowObjectDetection sample op mode, did you watch the camera preview on the Robot Controller (I'm assuming you are using an Android Phone as your robot controller) to see what TensorFlow thinks are the objects in its field of view?

Also, the TensorFlow frame rate for the phones that are used in FTC is relatively low.  When you do the test, was the robot moving quickly?  Have you tried a stationary test to start?

**Comment by ftctechnh** [comment]
Hello Hellositsme,

Here's a picture of a TensorFlow test op mode with the .tflite Skystone model.  Note that I don't have a screen grab right now of the Stones and Skystones side-by-side, but we tested this case as well and TensorFlow was able to reliably distinguish the Stones from the Skystones. If I have a chance this week I'll try and get a frame grab for you of the Stones and Skystones placed side-by-side (as they would be at the start of Autonomous).

![image](https://user-images.githubusercontent.com/12596789/64930011-84b8a500-d7fa-11e9-8e3d-9612b898ed0e.png)


You can see in the image the stones are labeled "first_element" and the Skystones are labeled "second_element".

**Comment by ftctechnh** [comment]
Also notice in the image above, I put the camera in Landscape mode and when I initialized TFOD, the camera was in this mode (and remained in this mode as I ran the op mode).

**Comment by FROGbots-4634** [comment]
@ftctechnh speaking of frame rate, one issue I've found with using Vuforia is that at first it runs fine, bu then the CPU begins to thermal throttle to around half it's maximum speed, and gets very laggy. I'm curious whether you noticed this in your testing? And if the phones with an aluminum body throttled less because they could dissipate the heat better?

**Comment by gearsincorg** [comment]
@FROGbots-4634 Are you running the preview window on the RC Phone?

Once we've tweaked our view, and debugged our auto, we always change the OpMode to NOT display the preview window.  This seems to reduce the power dissipation, and keeps the phone cooler.

**Comment by FROGbots-4634** [comment]
@gearsincorg oh that's a good point. I know that in my [EasyOpenCV](https://github.com/OpenFTC/EasyOpenCV) library disabling the viewport helps to keep the CPU from throttling, not sure why I didn't think of doing the same for Vuforia..... hmmmmm... something to test.

**Comment by ftctechnh** [comment]
@FROGbots-4634 
HI Frogbots - when you say that the CPU begins to thermal throttle, did you actually monitor the CPU temperatures and the core frequencies?  

I tested the TensorFlow using a pair of motorola Moto E4's and also a REV Control Hub (Rock chip android controller).   I did not notice the devices throttling the CPU, but was not monitoring the core temps or operating frequencies or checking for this behavior closely.

In the past, (a year ago?) when the Tech Team integrated support for the UVC webcams, we monitored the temperature for a typical autonomous op mode run using a UVC camera running Vuforia (doing the 2D target recognition and tracking).  In that scenario, while the temperature rose (and we had the camera preview enabled during our tests), for the length of a typical FTC match, the temperature rise did not have a significant negative effect.

However, I have not monitored the temperature when using TFOD.  Qualitatively, I did not notice a significant thermal slowdown, but I don't know for sure what was happening internally because I did not monitor the temperatures.

If you anyone is interested in monitoring the temperatures, I believe the following files are useful:

**/sys/devices/system/cpu/online** - I believe this will tell you how many CPUs are currently online.  You can type "cat /sys/devices/system/cpu/online" in a shell window and see what cores are currently working.

similarly,

**/sys/devices/virtual/thermal/thermal_zone0/temp** will give you the temp (Centigrade or millicentigrade) of core 0.  There are multiple zones that are monitored so there are multiple thermal_zones that you can access in /sys/devices/virtual/thermal.  I think an alternate/equivalent path to this data can be found here

**/sys/class/thermal/thermal_zone0/temp**

Lastly, I believe that you can monitor the current  cpu frequency using the following paths
**/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq**
**/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq**
etc.

**Comment by ftctechnh** [comment]
@Hellositsme 
Hi Hellositsme 

I ran the ConceptTensorFlowObjectDetection sample op mode on a Moto E4 Play this AM and grabbed some frames.  I tried adjusting the Confidence threshold to see if it would improve the accuracy of the bounding boxes (it did not). 

The detections are reasonably accurate, but there are instances where the bounding boxes extend beyond the size of a single Skystone.

For this season's game, a team can use TensorFlow or Vuforia to identify and track Skystones.

Vuforia has the advantage that it's detection rate will be very fast and localizing off of the image target on the Skystone should be very accurate.  However, Vuforia cannot detect the regular Stones, it only recognizes the Skystone 2d image target.

TensorFlow has a lower detection rate and the bounding boxes might be a little generous at times.  However, TensorFlow is useful because it can detect the Stones in this year's games.  Also, Tensorflow will detect the Skystones with reasonable accuracy, even when it doesn't have a great look at the sticker on the front.  Vuforia has to have a clear view of the sticker to identify it.  I don't think this matters much in this season's game, however.

If you use TensorFlow, you might need to adjust your op mode so it "aims for the middle" of the bounding box when attempting to grab/manipulate a Skystone.

I hope this helps!

![Screenshot_20190916-081544](https://user-images.githubusercontent.com/12596789/64957762-9da57280-d85b-11e9-9f46-0da20ed63633.png)

![Screenshot_20190916-081552](https://user-images.githubusercontent.com/12596789/64957763-9da57280-d85b-11e9-9fb6-1fb8232eb9f0.png)

![Screenshot_20190916-081557](https://user-images.githubusercontent.com/12596789/64957764-9da57280-d85b-11e9-876c-db742db868cc.png)

![Screenshot_20190916-081601](https://user-images.githubusercontent.com/12596789/64957765-9da57280-d85b-11e9-9c2a-9709f12234fc.png)

![Screenshot_20190916-081606](https://user-images.githubusercontent.com/12596789/64957766-9da57280-d85b-11e9-902a-bfe254779dbb.png)

**Comment by ftctechnh** [comment]
@FROGbots-4634 
Hi Frogbots 

Here is a script "print-thermal.sh" that I used to print the temps and freqs for my device:

**_print-thermal.sh_**
```
#!/bin/bash

#Temperature readings for all zones that produce some values
cpu0_temp=$(cat /sys/devices/virtual/thermal/thermal_zone0/temp)
cpu1_temp=$(cat /sys/devices/virtual/thermal/thermal_zone1/temp)
cpu2_temp=$(cat /sys/devices/virtual/thermal/thermal_zone2/temp)
cpu3_temp=$(cat /sys/devices/virtual/thermal/thermal_zone3/temp)
cpu4_temp=$(cat /sys/devices/virtual/thermal/thermal_zone4/temp)
cpu5_temp=$(cat /sys/devices/virtual/thermal/thermal_zone5/temp)
cpu6_temp=$(cat /sys/devices/virtual/thermal/thermal_zone6/temp)

#Currently number of online cores
cores_online=$(cat /sys/devices/system/cpu/online)

#Current frequency at which each core is running
[ -f '/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq' ] && cpu0_freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
[ -f '/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq' ] && cpu1_freq=$(cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq)
[ -f '/sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq' ] && cpu2_freq=$(cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq)
[ -f '/sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq' ] && cpu3_freq=$(cat /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq)

#Replace empty strings with 'offline' for offline cores
[ -z "$cpu0_freq" ] && cpu0_freq='offline'
[ -z "$cpu1_freq" ] && cpu1_freq='offline' 
[ -z "$cpu2_freq" ] && cpu2_freq='offline' 
[ -z "$cpu3_freq" ] && cpu3_freq='offline'

echo "$cores_online, $cpu0_freq, $cpu1_freq, $cpu2_freq, $cpu3_freq, $cpu0_temp, $cpu1_temp, $cpu2_temp, $cpu3_temp, $cpu4_temp, $cpu5_temp, $cpu6_temp"
```

Here's a script that I used to invoke print-thermal.sh repeatedly:

**_monitor-temp.sh_**
```
#!/bin/bash
# monitor temperature of the CPUs and the CPU frequencies (to see if thermal throttling is occurring).
PRINT_THERMAL="/sdcard/tmp/print-thermal.sh"

while true
do
	sh $PRINT_THERMAL
	sleep 1
done
```

Here is some sample output from my E4 (just idling - it's not running an op mode):
```
0-3, 960000, 960000, 960000, 960000, 28200, 28200, 28, 28, 28, 29, 34786
0-3, 960000, 960000, 960000, 960000, 28200, 28200, 28, 28, 28, 29, 34786
0-3, 1401000, 1401000, 1401000, 1401000, 28200, 28200, 28, 28, 28, 29, 34786
0-3, 960000, 960000, 960000, 960000, 28200, 28200, 28, 28, 28, 29, 34786
0-3, 960000, 960000, 960000, 960000, 28200, 28200, 28, 28, 28, 29, 34786
0-3, 960000, 960000, 960000, 960000, 28200, 28200, 28, 28, 28, 29, 34786
0-3, 1401000, 1401000, 1401000, 1401000, 28200, 28200, 28, 28, 28, 29, 34813
0-3, 960000, 960000, 960000, 960000, 28200, 28200, 28, 28, 28, 29, 34813
0-3, 960000, 960000, 960000, 960000, 27700, 27700, 28, 28, 28, 29, 34813
```

Important notes:
1. If you are editing these scripts on a Windows machine, make sure you use Linux style end of line conversions.  I recently switched from a Mac to a Windows machine and use Notepad++ to edit shell scripts.  Notepad++ has an **Edit->EOL Conversion** menu option that I set to **Unix (LF)** so that the file can be executed properly on the Android device.
2. I copied the scripts to a tmp directory (_/sdcard/tmp_) then using an adb shell, invoked the monitor temperature script using the _sh_ command (_sh /sdcard/tmp/monitor-tmp.sh_).

I hope this helps!

Tom

**Comment by ftctechnh** [comment]
@FROGbots-4634 
Frogbots - I just realized my answer might not have been clear.  Running Vuforia/TFOD does put a strain on the devices.  Over time, they will get warmer.  However, in past testing, for the length of a typical FTC match we didn't notice significant thermal effects when running Vuforia and doing 2d target detection and tracking.

I do notice that if I leave the op mode running for a while (several minutes) it does feel warm to the touch and I suspect some thermal throttling is going on.  However, for the length of an automous run, or even for a couple of minutes, i have not noticed this to be an issue.

If your bot is waiting for a match to begin and it has the Vuforia tracking enabled, if it waits a long time, I imagine it could get warmer.  You might want to consider not enabling the tracking in this case until after the start command has been received.

**Comment by FROGbots-4634** [comment]
@ftctechnh Yes I was indeed monitoring the temps and frequencies. I observed that it ran at 2.26GHz until the temp hit approximately 65C, at which point it began to throttle sharply, settling out at 1.19GHz within less than a minute. Just for curiosity's sake, I also disabled thermal throttling and locked all cores to max speed, and put the phone on an ice pack. I was monitoring temps while it was running, but it quickly got up to 85C which is the max the SOC is rated for so at that point I stopped it so as to not destroy something. Interestingly, the phone was, while quite warm, definitely not hot. I am left wondering whether this phone maybe doesn't have enough thermal paste between the SOC and the case or something....

**Comment by ftctechnh** [comment]
@FROGbots-4634 
Hi Frogbots - thanks for the feedback.  If I get time later this week I'll try some testing with my Moto E4's and monitor the temperature and clock speeds to see if I get similar results.  

That's a very dramatic jump in temperature! Definitely keep thermal throttling enabled!

Tom

**Comment by ftctechnh** [comment]
@Hellositsme 
There is a similar discussion over on Reddit.  Someone suggested decreasing the minimum confidence threshold from the default value of 0.80 to a lower value.  I tried this and switched it from 0.8 to 0.6 and the results look pretty good (see [YouTube Video here](https://youtu.be/zyX5suaBjqg)).

The Reddit thread can be found [here](https://www.reddit.com/r/FTC/comments/d4reqt/tensorflow_detects_the_skystone_and_makes_it_way/).

Perhaps if you try decreasing the minimumConfidence threshold you will get smaller bounding boxes since TensorFlow will be more likely to detect the Stone or Skystone adjacent to the target object.

**Comment by jrasor** [comment]
It works. On a G4 Play, it takes 1 - 2 seconds to make a decision. It can distinguish ordinary Stones from SkyStones, and gives screen coordinates to two opposite rectangle coordinates. We just took the stock Robot Controller 5.2 sample opmode and minimally modified it.

**Comment by cmacfarl** [comment]
This discussion is probably better taken to the forums or reddit.  Thank you.
